/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaintainance;

//
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static StockMaintainance.Shop.guitar;
import java.time.LocalDate;
import java.time.Year;
import java.time.format.DateTimeFormatter;
import loveguitar01.*;
import loveguitar01.median;

/**
 *
 * @author jeelk
 */
public class AddGuitar extends javax.swing.JFrame {

    /**
     * Creates new form Guitar
     */
    public AddGuitar() {
        initComponents();
        setFlagsVisible(false);
        statusComboBox.setEnabled(false);
        
        
       
        
    }
   
    
    
    public void resetFields(boolean option)
    {
          Date d=new Date();  
        int year=d.getYear();
        
        modelTextField.setText(""); serialNumberTextField.setText(""); yearPicker.setYear(d.getYear()); lengthTextField.setText(""); widthTextField.setText(""); heightTextField.setText("");
        rentTextField.setText(""); colorTextField.setText(""); SelectBuilder.setSelectedItem(null); typeComboBox.setSelectedItem(null); backWoodComboBox.setSelectedItem(null);
        topWoodCombox.setSelectedItem(null); 
    }
    
    
    public void setFlagsVisible(boolean option)
    {
       yearFlag.setVisible(option);
       serialFlag.setVisible(option);
       rentPerDayFlag.setVisible(option);
       lengthFlag.setVisible(option);
       widthFlag.setVisible(option);
       heightFlag.setVisible(option);
       colorFlag.setVisible(option);
    }
    
    
    public boolean isString(String str){
        return((str != null)
                && (!str.equals(""))
                && (str.matches("^[a-zA-Z]*$"))
                );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        testDayPicker1 = new com.qt.datapicker.TestDayPicker();
        com.qt.datapicker.TestDayPicker testDayPicker2 = new com.qt.datapicker.TestDayPicker();
        testDayPicker3 = new com.qt.datapicker.TestDayPicker();
        testDayPicker4 = new com.qt.datapicker.TestDayPicker();
        testDayPicker5 = new com.qt.datapicker.TestDayPicker();
        weekendConstraint1 = new org.jdatepicker.constraints.WeekendConstraint();
        weekendConstraint2 = new org.jdatepicker.constraints.WeekendConstraint();
        weekendConstraint3 = new org.jdatepicker.constraints.WeekendConstraint();
        serialFlag2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rentTextField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        SelectBuilder = new javax.swing.JComboBox<>();
        typeComboBox = new javax.swing.JComboBox<>();
        backWoodComboBox = new javax.swing.JComboBox<>();
        modelTextField = new javax.swing.JTextField();
        serialNumberTextField = new javax.swing.JTextField();
        widthTextField = new javax.swing.JTextField();
        lengthTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        topWoodCombox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        backButtonAdd = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        yearFlag = new javax.swing.JLabel();
        serialFlag = new javax.swing.JLabel();
        lengthFlag = new javax.swing.JLabel();
        widthFlag = new javax.swing.JLabel();
        rentFlag = new javax.swing.JLabel();
        heightFlag = new javax.swing.JLabel();
        rentPerDayFlag = new javax.swing.JLabel();
        yearPicker = new com.toedter.calendar.JYearChooser();
        colorFlag = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        serialFlag2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        serialFlag2.setForeground(new java.awt.Color(255, 0, 51));
        serialFlag2.setText("!!Error");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD GUITAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        jLabel1.setText("Type:");

        jLabel2.setText("Model:");

        jLabel3.setText("Builder:");

        jLabel4.setText("Width(in inch):");

        jLabel5.setText("Back Wood:");

        jLabel7.setText("Top Wood:");

        jLabel8.setText("Serial Number:");

        jLabel9.setText("Year:");

        jLabel10.setText("Rent per Day:");

        jLabel11.setText("Colour:");

        jLabel12.setText("Length(in inch):");

        jLabel13.setText("Status:");

        jLabel14.setText("Height(in inch):");

        rentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentTextFieldActionPerformed(evt);
            }
        });

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Under_Maintenance" }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        SelectBuilder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FENDER", "MARTIN", "GIBSON", "COLLINGS", "OLSON", "RYAN", "PARAS", "RAJ" }));
        SelectBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBuilderActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACOUSTIC", "ELECTRIC" }));

        backWoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA" }));
        backWoodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backWoodComboBoxActionPerformed(evt);
            }
        });

        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        serialNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumberTextFieldActionPerformed(evt);
            }
        });

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        lengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthTextFieldActionPerformed(evt);
            }
        });

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        colorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextFieldActionPerformed(evt);
            }
        });

        topWoodCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA" }));

        addButton.setText("Add Guitar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButtonAdd.setText("Back");
        backButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonAddActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        yearFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        yearFlag.setForeground(new java.awt.Color(255, 0, 51));
        yearFlag.setText("Please Enter Valid Year");

        serialFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        serialFlag.setForeground(new java.awt.Color(255, 0, 51));
        serialFlag.setText("Enter only Number");

        lengthFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lengthFlag.setForeground(new java.awt.Color(255, 0, 51));
        lengthFlag.setText("Please enter valid Length");

        widthFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        widthFlag.setForeground(new java.awt.Color(255, 0, 51));
        widthFlag.setText("Please enter valid Width");

        rentFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rentFlag.setForeground(new java.awt.Color(255, 0, 51));
        rentFlag.setText("Please Enter vaild amount");

        heightFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        heightFlag.setForeground(new java.awt.Color(255, 0, 51));
        heightFlag.setText("Please enter vaild Height");

        rentPerDayFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rentPerDayFlag.setForeground(new java.awt.Color(255, 0, 51));
        rentPerDayFlag.setText("Please Enter Valid Rent");

        yearPicker.setDayChooser(null);
        yearPicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearPickerKeyTyped(evt);
            }
        });

        colorFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        colorFlag.setForeground(new java.awt.Color(255, 0, 51));
        colorFlag.setText("Please Enter Color as Text");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentPerDayFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(1064, 1064, 1064))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SelectBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(topWoodCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(widthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addButton)
                        .addGap(150, 150, 150)
                        .addComponent(resetButton)
                        .addGap(135, 135, 135)
                        .addComponent(searchButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(backButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topWoodCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentPerDayFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(resetButton)
                            .addComponent(searchButton)))
                    .addComponent(yearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentTextFieldActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void serialNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumberTextFieldActionPerformed

    private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthTextFieldActionPerformed

    private void lengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthTextFieldActionPerformed

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void colorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        
        String model = modelTextField.getText();
        String builder = SelectBuilder.getSelectedItem().toString();
        String  type = typeComboBox.getSelectedItem().toString();
        String backWood = backWoodComboBox.getSelectedItem().toString();
        String topWood = topWoodCombox.getSelectedItem().toString();
        String color = colorTextField.getText();
        int year = yearPicker.getYear();
        
        if(year > 2021)
       {
               //JOptionPane.showMessageDialog(this, "Invalid Year");
                 flag = 1;
                 yearFlag.setVisible(true);    
                  
       }
      
        
        int serialNumber=0;
        try{
        serialNumber = Integer.parseInt(serialNumberTextField.getText());
        
        for(int i=0;i<guitar.size();i++)
        {
            if(guitar.get(i).getSerialNumber()==serialNumber)
            {
                JOptionPane.showMessageDialog(this, "Serial number already exists");
                flag = 1;
                
            }
        }
        }
        catch(Exception ex)
        {
            //JOptionPane.showMessageDialog(this, "Invalid Serial Number");
            flag = 1;
            serialFlag.setVisible(true);
        }
       
        double rentCost =0;
        try{
        rentCost = Double.parseDouble(rentTextField.getText());
        }
        catch (Exception ex)
        {
           // JOptionPane.showMessageDialog(this, "Invalid Rent");
            flag =1;
            rentPerDayFlag.setVisible(true);
        }
      /*  try
        {
            String color = colorTextField.getText();
            boolean isText = isString(color);
            if(isText == false)
            {
                flag =1;
                colorFlag.setVisible(true);
            }
        }
        catch(Exception ex)
        {
            
        }*/
        double length = 0;
        try
        {
            length = Double.parseDouble(lengthTextField.getText());
        }
        catch (Exception ex)
        {
          // JOptionPane.showMessageDialog(this, "Invalid Length"); 
            flag = 1;
            lengthFlag.setVisible(true);
        }
        double height = 0;
        try
        {
            height = Double.parseDouble(heightTextField.getText());
        }
        catch(Exception ex)
        {
          //  JOptionPane.showMessageDialog(this, "Invalid Height"); 
            flag =1;
            heightFlag.setVisible(true);
        }
        double width =0;
        try
        {
            
            width = Double.parseDouble(widthTextField.getText());
        }
        catch(Exception ex)
        {
           // JOptionPane.showMessageDialog(this, "Invalid Width"); 
            flag = 1;
            widthFlag.setVisible(true);
        }
        
    
        Guitar gt1 = new Guitar(model, Builder.valueOf(builder), StockMaintainance.Type.valueOf(type), Wood.valueOf(backWood), Wood.valueOf(topWood), serialNumber, year, rentCost, color, length, height, width, Status.AVAILABLE);
        if(flag ==0)
        {
            guitar.add(gt1);
            JOptionPane.showMessageDialog(this, "Guitar Added Successfully!!");
            resetFields(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter the required fields");
        }
               
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonAddActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new median().setVisible(true);
    }//GEN-LAST:event_backButtonAddActionPerformed

    Guitar searchGuitar(int serialNumber)
    {
        Guitar found = null;
        for(Guitar g: guitar)
        {
            if(g.getSerialNumber() == serialNumber)
            {
                found = g;
                break;
            }
        }
        return found;
    }
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        int serialNumber = Integer.parseInt(serialNumberTextField.getText());
        Guitar g = searchGuitar(serialNumber);
        if(g ==null)
        {
            JOptionPane.showMessageDialog(this, "Sorry Guitar not found matching with this id");
        }
        else
        {
            
            JOptionPane.showMessageDialog(this, "Guitar found matching with this id");
            modelTextField.setText(g.getModel());
            SelectBuilder.getModel().setSelectedItem(g.getBuilder());
            typeComboBox.getModel().setSelectedItem(g.getType());
            backWoodComboBox.getModel().setSelectedItem(g.getBackWood());
            topWoodCombox.getModel().setSelectedItem(g.getTopWood());
            yearPicker.setYear(g.getYear());
            rentTextField.setText(g.getRentCost()+"");
            colorTextField.setText(g.getColor());
            lengthTextField.setText(g.getLength()+"");
            widthTextField.setText(g.getWidth()+"");
            heightTextField.setText(g.getHeight()+"");
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void SelectBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBuilderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectBuilderActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetFields(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void backWoodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backWoodComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backWoodComboBoxActionPerformed

    private void yearPickerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearPickerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_yearPickerKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGuitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectBuilder;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButtonAdd;
    private javax.swing.JComboBox<String> backWoodComboBox;
    private javax.swing.JLabel colorFlag;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel heightFlag;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lengthFlag;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel rentFlag;
    private javax.swing.JLabel rentPerDayFlag;
    private javax.swing.JTextField rentTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel serialFlag;
    private javax.swing.JLabel serialFlag2;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JComboBox<String> statusComboBox;
    private com.qt.datapicker.TestDayPicker testDayPicker1;
    private com.qt.datapicker.TestDayPicker testDayPicker3;
    private com.qt.datapicker.TestDayPicker testDayPicker4;
    private com.qt.datapicker.TestDayPicker testDayPicker5;
    private javax.swing.JComboBox<String> topWoodCombox;
    private javax.swing.JComboBox<String> typeComboBox;
    private org.jdatepicker.constraints.WeekendConstraint weekendConstraint1;
    private org.jdatepicker.constraints.WeekendConstraint weekendConstraint2;
    private org.jdatepicker.constraints.WeekendConstraint weekendConstraint3;
    private javax.swing.JLabel widthFlag;
    private javax.swing.JTextField widthTextField;
    private javax.swing.JLabel yearFlag;
    private com.toedter.calendar.JYearChooser yearPicker;
    // End of variables declaration//GEN-END:variables
}
