/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaintainance;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import StockMaintainance.Guitar;
import StockMaintainance.AddGuitar;
import StockMaintainance.LoveGuitar01;
import loveguitar01.median;


/**
 *
 * @author jeelk
 */
public class GuitarAvailabilityForm extends javax.swing.JFrame {
    private Iterable<Guitar> guitar;
    //private String statusComboBox;

    /**
     * Creates new form GuitarAvailabilityForm
     */
    public GuitarAvailabilityForm() {
        
        initComponents();
        setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel)availableTable.getModel();
        Object[] rowData = new Object[13];
        for (int i = 0 ; i <Shop.guitar.size(); i++)
       //for(Guitar g : guitar)
       {
            if(Shop.guitar.get(i).getStatus().equals(Status.AVAILABLE))
                {

                   rowData[0] = Shop.guitar.get(i).getSerialNumber();
                   rowData[1] = Shop.guitar.get(i).getModel();
                   rowData[2] = Shop.guitar.get(i).getBuilder();
                   rowData[3] = Shop.guitar.get(i).getType();
                   rowData[4] = Shop.guitar.get(i).getTopWood();
                   rowData[5] = Shop.guitar.get(i).getBackWood();
                   rowData[6] = Shop.guitar.get(i).getRentCost();
                   rowData[7] = Shop.guitar.get(i).getYear();
                   rowData[8] = Shop.guitar.get(i).getColor();
                   rowData[9] = Shop.guitar.get(i).getLength();
                   rowData[10] = Shop.guitar.get(i).getWidth();
                   rowData[11] = Shop.guitar.get(i).getHeight();
                   rowData[12] = Shop.guitar.get(i).getStatus();
                   model.addRow(rowData);
               }
            
                }
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        availableTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        availableTable.setBackground(new java.awt.Color(255, 204, 204));
        availableTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        availableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR NO.", "Model", "Builder", "Type", "Top Wood", "Back Wood", "Rent", "Year", "Colour", "Length", "Width", "Height", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(availableTable);
        if (availableTable.getColumnModel().getColumnCount() > 0) {
            availableTable.getColumnModel().getColumn(0).setResizable(false);
            availableTable.getColumnModel().getColumn(1).setResizable(false);
            availableTable.getColumnModel().getColumn(2).setResizable(false);
            availableTable.getColumnModel().getColumn(3).setResizable(false);
            availableTable.getColumnModel().getColumn(4).setResizable(false);
            availableTable.getColumnModel().getColumn(5).setResizable(false);
            availableTable.getColumnModel().getColumn(6).setResizable(false);
            availableTable.getColumnModel().getColumn(7).setResizable(false);
            availableTable.getColumnModel().getColumn(8).setResizable(false);
            availableTable.getColumnModel().getColumn(9).setResizable(false);
            availableTable.getColumnModel().getColumn(10).setResizable(false);
            availableTable.getColumnModel().getColumn(11).setResizable(false);
            availableTable.getColumnModel().getColumn(12).setResizable(false);
        }

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(842, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new median().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuitarAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuitarAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuitarAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuitarAvailabilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GuitarAvailabilityForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable availableTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

  
}
