/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaintainance;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static StockMaintainance.Shop.guitar;
import loveguitar01.median;
import loveguitar01.*;

/**
 *
 * @author jeelk
 */
public class SearchUpdateGuitarForm extends javax.swing.JFrame  {

    //private Iterable<Guitar> guitars;

    /**
     * Creates new form SearchGuitarForm
     */
    public SearchUpdateGuitarForm() {
        initComponents();
        isVisible(false);
        isEditable(false);
        setFlagsVisible(false);
    }
   
    public void isVisible(boolean option)
    {
        builderLabel.setVisible(option); builderComboBox.setVisible(option);
        typeLabel.setVisible(option); typeComboBox.setVisible(option);
        backWoodLabel.setVisible(option); backWoodComboBox.setVisible(option);
        topWoodLabel.setVisible(option); topWoodCombox.setVisible(option);
        modelLabel.setVisible(option); modelTextField.setVisible(option);
        yearLabel.setVisible(option); yearPicker.setVisible(option);
        rentLabel.setVisible(option); rentTextField.setVisible(option);
        colourLabel.setVisible(option); colorTextField.setVisible(option);
        lengthLabel.setVisible(option); lengthTextField.setVisible(option);
        widthLabel.setVisible(option); widthTextField.setVisible(option);
        heightLabel.setVisible(option); heightTextField.setVisible(option);
        statusLabel.setVisible(option); statusComboBox.setVisible(option);
        //rentDateLabel.setVisible(option); rentDate.setVisible(option);
        //dueDateLabel.setVisible(option); dueDate.setVisible(option);
        updateButton.setVisible(option);
        saveButton.setVisible(option);
    }
    
    public void isEditable(boolean option)
    {
        builderComboBox.setEnabled(option);
        typeComboBox.setEnabled(option);
        backWoodComboBox.setEnabled(option);
        topWoodCombox.setEnabled(option);
        modelTextField.setEditable(option);
        yearPicker.setEnabled(option);
        rentTextField.setEditable(option);
        colorTextField.setEditable(option);
        lengthTextField.setEditable(option);
        widthTextField.setEditable(option);
        heightTextField.setEditable(option);
        statusComboBox.setEnabled(option);
        //rentDate.setEnabled(option);
        //dueDate.setEnabled(option);
       
    }
    
     public void setFlagsVisible(boolean option)
    {
       yearFlag.setVisible(option);
       //serialFlag.setVisible(option);
       rentPerDayFlag.setVisible(option);
       lengthFlag.setVisible(option);
       widthFlag.setVisible(option);
       heightFlag.setVisible(option);
    }
    
      public void resetFields()
    {
        modelTextField.setText(""); serialNumberTextField.setText(""); yearPicker.setYear(2021); lengthTextField.setText(""); widthTextField.setText(""); heightTextField.setText("");
        rentTextField.setText(""); colorTextField.setText(""); builderComboBox.setSelectedItem(null); typeComboBox.setSelectedItem(null); backWoodComboBox.setSelectedItem(null);
        topWoodCombox.setSelectedItem(null); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        builderLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        backWoodLabel = new javax.swing.JLabel();
        topWoodLabel = new javax.swing.JLabel();
        serialNoLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();
        colourLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        rentTextField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        builderComboBox = new javax.swing.JComboBox<>();
        typeComboBox = new javax.swing.JComboBox<>();
        backWoodComboBox = new javax.swing.JComboBox<>();
        modelTextField = new javax.swing.JTextField();
        serialNumberTextField = new javax.swing.JTextField();
        widthTextField = new javax.swing.JTextField();
        lengthTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        topWoodCombox = new javax.swing.JComboBox<>();
        backButtonAdd = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        updateButton = new javax.swing.JToggleButton();
        saveButton = new javax.swing.JButton();
        yearFlag = new javax.swing.JLabel();
        lengthFlag = new javax.swing.JLabel();
        widthFlag = new javax.swing.JLabel();
        heightFlag = new javax.swing.JLabel();
        rentPerDayFlag = new javax.swing.JLabel();
        yearPicker = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH OR UPDATE GUITAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        typeLabel.setText("Type:");

        modelLabel.setText("Model:");

        builderLabel.setText("Builder:");

        widthLabel.setText("Width:");

        backWoodLabel.setText("Back Wood:");

        topWoodLabel.setText("Top Wood:");

        serialNoLabel.setText("Serial Number:");

        yearLabel.setText("Year:");

        rentLabel.setText("Rent per Day:");

        colourLabel.setText("Colour:");

        lengthLabel.setText("Length:");

        statusLabel.setText("Status:");

        heightLabel.setText("Height:");

        rentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentTextFieldActionPerformed(evt);
            }
        });

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNDER_MAINTENANCE" }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        builderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FENDER", "MARTIN", "GIBSON", "COLLINGS", "OLSON", "RYAN", "PARAS", "RAJ" }));
        builderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                builderComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACOUSTIC", "ELECTRIC" }));

        backWoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA  " }));

        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        serialNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumberTextFieldActionPerformed(evt);
            }
        });

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        lengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthTextFieldActionPerformed(evt);
            }
        });

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        colorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextFieldActionPerformed(evt);
            }
        });

        topWoodCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA  " }));

        backButtonAdd.setText("Back");
        backButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonAddActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update Record");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        yearFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        yearFlag.setForeground(new java.awt.Color(255, 0, 51));
        yearFlag.setText("Please Enter Valid Year");

        lengthFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lengthFlag.setForeground(new java.awt.Color(255, 0, 51));
        lengthFlag.setText("Please enter valid Length");

        widthFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        widthFlag.setForeground(new java.awt.Color(255, 0, 51));
        widthFlag.setText("Please enter valid Width");

        heightFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        heightFlag.setForeground(new java.awt.Color(255, 0, 51));
        heightFlag.setText("Please enter vaild Height");

        rentPerDayFlag.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rentPerDayFlag.setForeground(new java.awt.Color(255, 0, 51));
        rentPerDayFlag.setText("Please Enter Valid Rent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(348, 348, 348))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serialNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(builderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(builderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(backWoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(topWoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(topWoodCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentPerDayFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(saveButton)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(serialNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backButtonAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(updateButton))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(builderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(builderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backWoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topWoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topWoodCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentPerDayFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(yearFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lengthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(widthFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heightFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(saveButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentTextFieldActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void builderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_builderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_builderComboBoxActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void serialNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumberTextFieldActionPerformed

    private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthTextFieldActionPerformed

    private void lengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthTextFieldActionPerformed

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void colorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextFieldActionPerformed

    private void backButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonAddActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new median().setVisible(true);
    }//GEN-LAST:event_backButtonAddActionPerformed

     Guitar searchGuitar(int serialNumber)
    {
        Guitar found = null;
        for(Guitar g: guitar)
        {
            if(g.getSerialNumber() == serialNumber)
            {
                found = g;
                break;
            }
        }
        return found;
    }
     
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
        int serialNumber = Integer.parseInt(serialNumberTextField.getText());
        Guitar g = searchGuitar(serialNumber);
       for(Guitar gt : guitar)
        if(gt.getSerialNumber() == serialNumber)
        {
            g = gt;
            break;
        }
        if(g == null)
        {
       JOptionPane.showMessageDialog(this, "No Guitar found with this matching Serial Number");
        }
        else
        {

            JOptionPane.showMessageDialog(this, "Guitar found matching with this id");
            modelTextField.setText(g.getModel());
            builderComboBox.getModel().setSelectedItem(g.getBuilder());
            typeComboBox.getModel().setSelectedItem(g.getType());
            backWoodComboBox.getModel().setSelectedItem(g.getBackWood());
            topWoodCombox.getModel().setSelectedItem(g.getTopWood());
            statusComboBox.getModel().setSelectedItem(g.getStatus());
            yearPicker.setYear(g.getYear());
            rentTextField.setText(g.getRentCost()+"");
            colorTextField.setText(g.getColor());
            lengthTextField.setText(g.getLength()+"");
            widthTextField.setText(g.getWidth()+"");
            heightTextField.setText(g.getHeight()+"");
            //rentDate.setDate(found.getRentedDate());
            //dueDate.setDate(found.getDueDate());
            isVisible(true);

        }
        
        
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Please enter Valid Serial Number");
        }
     
        

    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        isEditable(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    
  
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int serialNumber = Integer.parseInt(serialNumberTextField.getText());
        String builder =  (String) builderComboBox.getSelectedItem().toString();
        String type = (String) typeComboBox.getSelectedItem().toString();
        String backWood = (String) backWoodComboBox.getSelectedItem().toString();
        String topWood = (String) topWoodCombox.getSelectedItem().toString();
        String status = (String) statusComboBox.getSelectedItem().toString();
        String model = modelTextField.getText();
        int year = yearPicker.getYear();
       int flag = 0;
        
        /*int year=0;
        try{
        year = Integer.parseInt(yearTextField.getText());
        }
        catch (Exception ex)
        {
           // JOptionPane.showMessageDialog(this, "Invalid Year");
            flag = 1;
            yearFlag.setVisible(true);
        }*/
        double rentCost =0;
        try{
        rentCost = Double.parseDouble(rentTextField.getText().toString());
        }
        catch (Exception ex)
        {
           // JOptionPane.showMessageDialog(this, "Invalid Rent");
            flag =1;
            rentPerDayFlag.setVisible(true);
        }
       String color = colorTextField.getText();
        double length = 0;
        try
        {
            length = Double.parseDouble(lengthTextField.getText());
        }
        catch (Exception ex)
        {
           //JOptionPane.showMessageDialog(this, "Invalid Length"); 
            flag = 1;
            lengthFlag.setVisible(true);
        }
        double height = 0;
        try
        {
            height = Double.parseDouble(heightTextField.getText());
        }
        catch(Exception ex)
        {
           // JOptionPane.showMessageDialog(this, "Invalid Height"); 
            flag =1;
            heightFlag.setVisible(true);
        }
        double width =0;
        try
        {
            
            width = Double.parseDouble(widthTextField.getText());
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Invalid Width"); 
            flag = 1;
            widthFlag.setVisible(true);
        }
        
    
       
       
       
        
        if(flag ==0)
        {
        int serialID = Integer.parseInt(serialNumberTextField.getText());
            Guitar gt = searchGuitar(serialID);
            gt.setBuilder(Builder.valueOf(builderComboBox.getSelectedItem().toString()));
            gt.setBackWood(Wood.valueOf(backWoodComboBox.getSelectedItem().toString()));
            gt.setType(StockMaintainance.Type.valueOf(typeComboBox.getSelectedItem().toString()));
            gt.setTopWood(Wood.valueOf(topWoodCombox.getSelectedItem().toString()));
            gt.setStatus(Status.valueOf(statusComboBox.getSelectedItem().toString()));
            gt.setModel(model);
            gt.setColor(color);
            gt.setLength(length);
            gt.setWidth(width);
            gt.setHeight(height);
            gt.setYear(year);
            gt.setRentCost(rentCost);
            
           JOptionPane.showMessageDialog(this, "Updated");
           resetFields();
            isVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter the required fields");
        }
        
      
        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateGuitarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateGuitarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateGuitarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateGuitarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUpdateGuitarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonAdd;
    private javax.swing.JComboBox<String> backWoodComboBox;
    private javax.swing.JLabel backWoodLabel;
    private javax.swing.JComboBox<String> builderComboBox;
    private javax.swing.JLabel builderLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel colourLabel;
    private javax.swing.JLabel heightFlag;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lengthFlag;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JLabel rentPerDayFlag;
    private javax.swing.JTextField rentTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel serialNoLabel;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> topWoodCombox;
    private javax.swing.JLabel topWoodLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JToggleButton updateButton;
    private javax.swing.JLabel widthFlag;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    private javax.swing.JLabel yearFlag;
    private javax.swing.JLabel yearLabel;
    private com.toedter.calendar.JYearChooser yearPicker;
    // End of variables declaration//GEN-END:variables


}
